spring.application.name=finbank
server.port=8080

spring.mongodb.uri=mongodb+srv://admin:Sweetu16@cluster.qljq7ku.mongodb.net/finbank?retryWrites=true&w=majority&appName=Cluster

jwt.secret=FinBankSuperSecretKey2024FinBankSuperSecretKey2024
jwt.expiration=86400000